RESTORE DATABASE apimgtdb FROM DISK ='/backups/apimgtdb.bak'
WITH NORECOVERY
GO
RESTORE DATABASE apimgtdb WITH RECOVERY
GO

RESTORE DATABASE regdb FROM DISK ='/backups/regdb.bak'
WITH NORECOVERY
GO
RESTORE DATABASE regdb WITH RECOVERY
GO

RESTORE DATABASE userdb FROM DISK ='/backups/userdb.bak'
WITH NORECOVERY
GO
RESTORE DATABASE userdb WITH RECOVERY
GO